#!/bin/bash
echo "Loading help..."
echo ""
echo ""

echo "DevFlow PM - Project Management System"
echo "======================================="
echo ""
echo "Quick Start Workflow"
echo "  1. /devflow:principles           - Define project principles"
echo "  2. /pm:prd-new <name>            - Create a new PRD"
echo "  3. /pm:spec-create <name>        - Formalize PRD into spec"
echo "  4. /pm:spec-clarify <name>       - Resolve spec ambiguities"
echo "  5. /pm:plan <name>               - Create technical plan"
echo "  6. /pm:epic-decompose <name>     - Break into tasks"
echo "  7. /pm:epic-sync <name>          - Push to GitHub"
echo "  8. /pm:epic-start <name>         - Start parallel execution"
echo ""
echo "PRD Commands"
echo "  /pm:prd-new <name>       - Launch brainstorming for new PRD"
echo "  /pm:prd-edit <name>      - Edit existing PRD"
echo "  /pm:prd-list             - List all PRDs"
echo "  /pm:prd-status           - Show PRD implementation status"
echo ""
echo "Spec Commands"
echo "  /pm:spec-create <name>   - Create spec from PRD"
echo "  /pm:spec-clarify <name>  - Resolve spec ambiguities (Q&A)"
echo "  /pm:spec-analyze <name>  - Cross-artifact consistency check"
echo "  /pm:plan <name>          - Create technical plan from spec"
echo ""
echo "Epic Commands"
echo "  /pm:epic-decompose <name>  - Break plan into task files"
echo "  /pm:epic-sync <name>       - Push epic and tasks to GitHub"
echo "  /pm:epic-start <name>      - Launch parallel agent execution"
echo "  /pm:epic-list              - List all epics"
echo "  /pm:epic-show <name>       - Display epic and its tasks"
echo "  /pm:epic-status [name]     - Show epic progress"
echo "  /pm:epic-close <name>      - Mark epic as complete"
echo ""
echo "Issue Commands"
echo "  /pm:issue-show <num>       - Display issue details"
echo "  /pm:issue-start <num>      - Begin work on issue"
echo "  /pm:issue-sync <num>       - Push updates to GitHub"
echo "  /pm:issue-close <num>      - Mark issue as complete"
echo ""
echo "Workflow Commands"
echo "  /pm:next                 - Show next priority tasks"
echo "  /pm:status               - Overall project dashboard"
echo "  /pm:standup              - Daily standup report"
echo "  /pm:blocked              - Show blocked tasks"
echo "  /pm:in-progress          - List work in progress"
echo ""
echo "Context Commands"
echo "  /context:create          - Generate baseline context docs"
echo "  /context:update          - Refresh context docs"
echo "  /context:prime           - Load context for new session"
echo ""
echo "Maintenance Commands"
echo "  /pm:validate             - Check system integrity"
echo "  /pm:search <query>       - Search across all content"
echo ""
echo "Setup Commands"
echo "  /pm:init                 - Install dependencies and configure"
echo "  /devflow:principles      - Define project principles"
echo "  /pm:help                 - Show this help message"
echo ""
echo "Tips"
echo "  - Use /pm:next to find available work"
echo "  - Run /pm:status for quick overview"
echo "  - Full workflow: prd-new -> spec-create -> plan -> epic-decompose -> epic-sync"
echo "  - Default backend: Python + FastAPI + PostgreSQL"

exit 0
